# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flipkart',
            old_name='name',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='flipkart',
            old_name='url',
            new_name='p_url',
        ),
    ]
