# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipkart',
            name='img_url',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='infibeam',
            name='img_url',
            field=models.TextField(default='None'),
        ),
    ]
