# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20170304_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flipkart',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='infibeam',
            name='img_url',
        ),
    ]
