# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20170304_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='snapdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
