# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_user_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=100)),
                ('match_p_id', models.CharField(max_length=100)),
                ('p_seller', models.CharField(max_length=100)),
                ('match_seller', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=100)),
                ('p_id', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
            ],
        ),
    ]
