# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='wishes',
        ),
    ]
